Class {
	#name : #KincWindowFeature,
	#superclass : #Object,
	#category : #Kinc
}

{ #category : #'as yet unclassified' }
KincWindowFeature class >> borderless [
	^2
]

{ #category : #'as yet unclassified' }
KincWindowFeature class >> maximizable [
	^8
]

{ #category : #'as yet unclassified' }
KincWindowFeature class >> minimizable [
	^1
]

{ #category : #'as yet unclassified' }
KincWindowFeature class >> onTop [
	^4
]

{ #category : #'as yet unclassified' }
KincWindowFeature class >> resizable [
	^16
]
